print("hello world")
kata=input("masukkan kata:")
print("jumlah huruf yang diinputkan :",len(kata))
kata2=kata.split()
print("jumlah kata =",len(kata2))
print("huruf depannya adalah :", kata[0])
print("huruf depannya adalah :", kata[-1])
